/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-primary-fixed": "#001f24",
        "inverse-on-surface": "#2f3035",
        "on-error-container": "#ffdad6",
        "on-background": "#e2e2e8",
        "on-tertiary-fixed-variant": "#594400",
        "on-tertiary-fixed": "#251a00",
        "surface-tint": "#00daf3",
        "surface-variant": "#333539",
        "inverse-surface": "#e2e2e8",
        "outline-variant": "#3b494c",
        "tertiary-container": "#fec931",
        "primary-fixed": "#9cf0ff",
        "background": "#111318",
        "tertiary-fixed": "#ffdf96",
        "primary-fixed-dim": "#00daf3",
        "outline": "#849396",
        "on-secondary-fixed-variant": "#0d4e57",
        "surface-container-high": "#282a2e",
        "tertiary-fixed-dim": "#f3bf26",
        "secondary-container": "#11505a",
        "surface": "#111318",
        "surface-dim": "#111318",
        "on-primary-container": "#00626e",
        "primary-container": "#00e5ff",
        "surface-container-low": "#1a1c20",
        "secondary-fixed-dim": "#98d0da",
        "secondary": "#98d0da",
        "on-tertiary-container": "#6f5500",
        "surface-container-lowest": "#0c0e12",
        "on-secondary-container": "#8ac1cc",
        "on-surface": "#e2e2e8",
        "on-surface-variant": "#bac9cc",
        "on-tertiary": "#3e2e00",
        "on-primary": "#00363d",
        "on-secondary": "#00363d",
        "secondary-fixed": "#b3ecf7",
        "inverse-primary": "#006875",
        "primary": "#c3f5ff",
        "on-secondary-fixed": "#001f24",
        "tertiary": "#ffeac0",
        "error-container": "#93000a",
        "surface-container": "#1e2024",
        "surface-bright": "#37393e",
        "on-primary-fixed-variant": "#004f58",
        "surface-container-highest": "#333539",
        "error": "#ffb4ab",
        "on-error": "#690005"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "headline": ["Epilogue"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      }
    },
  },
  plugins: [],
};